### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by bergtwvd** [ElasticBox/elastickube#126]
Upon creating initial account I get

````
Internet Connection
Requesting "http://google.com" failed: "[Errno 101] Network is unreachable". Report this
````

Other items have a check.

* Running Kubernetes 1.5.0
* Nginx proxy with https setup, port 443, runs on Kubernetes master
* ElasticKube sits behind the nginx proxy
* There is a second corporate proxy between the Kubernetes hosts and the world

Why is access to google.com needed?

Also, can ElasticKube work in this setup?

Maybe related to https://github.com/ElasticBox/elastickube/issues/127

**Comment by bergtwvd** [comment]
Resolved by #127

**Comment by bergtwvd** [comment]
Forgot to add that I set the env CHECK_CONNECTIVITY_URL for the elastickube-diagnostics container to localhost (probably due to proxy):

````
      - name: elastickube-diagnostics
        image: elasticbox/elastickube-diagnostics:${VERSION}
        env:
        - name: HTTPS_PROXY
          value: "https://xxx.xxx.xxx:8080"
        - name: HTTP_PROXY
          value: "http://xxx.xxx.xxx:8080"
        - name: CHECK_CONNECTIVITY_URL
          value: "http://localhost"
 ````
